name: 'Check all'
description: 'Composite Actions for TSN Lab'

inputs:
  python_version:
    description: 'Python version'
    default: '3.12'
  rust_version:
    description: 'Rust version'
    default: 'stable'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        repository: 'tsnlab/check'
        path: '.github/check'

    - name: 'Basic'
      uses: ./.github/check/actions/basic

    - name: 'Python'
      uses: ./.github/check/actions/python
      with:
        python_version: ${{ inputs.python_version }}

    - name: 'Rust'
      uses: ./.github/check/actions/rust
      with:
        rust_version: ${{ inputs.rust_version }}

    - name: 'C/CPP'
      uses: ./.github/check/actions/cpp
