name: 'Check all'
description: 'Composite Actions for TSN Lab'

inputs:
  python_version:
    description: 'Python version'
    default: '3.12'
  rust_version:
    description: 'Rust version'
    default: 'stable'
  github_token:
    description: 'GITHUB_TOKEN secret'
    required: true
  shellcheck_ignore_paths:
    description: 'Paths to ignore in shellcheck'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        repository: 'tsnlab/check'
        path: '.github/check'

    - name: 'Basic'
      uses: ./.github/check/actions/basic
      with:
        github_token: ${{ inputs.github_token }}
        shellcheck_ignore_paths: ${{ inputs.shellcheck_ignore_paths }}

    - name: 'Python'
      if: ${{ hashFiles('pyproject.toml') != '' }}
      uses: ./.github/check/actions/python
      with:
        python_version: ${{ inputs.python_version }}

    - name: 'Rust'
      if: ${{ hashFiles('Cargo.toml') != '' }}
      uses: ./.github/check/actions/rust
      with:
        github_token: ${{ inputs.github_token }}
        rust_version: ${{ inputs.rust_version }}

    - name: 'C/CPP'
      if: ${{ hashFiles('Makefile') != '' || hashFiles('CMakeLists.txt') != '' }}
      uses: ./.github/check/actions/cpp
