name: Rust

inputs:
  github_token:
    description: 'GITHUB_TOKEN secret'
    required: true
  rust_version:
    description: 'Rust version'
    default: 'stable'

runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ github.event.inputs.rust_version }}
        components: clippy, rustfmt
    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
    - name: Cargo fmt
      uses: actions-rust-lang/rustfmt@v1
    - name: Cargo clippy
      uses: giraffate/clippy-action@v1
      with:
        github_token: ${{ inputs.github_token }}
    - name: Test Rust
      run: cargo test
      shell: bash
    - name: Build Rust
      run: cargo build --release
      shell: bash
