name: 'C/CPP'
description: 'Lint C/CPP files'

inputs:
  github_token:
    description: 'GITHUB_TOKEN secret'
    required: true

runs:
  using: composite
  steps:
    - name: Run clang-format, clang-tidy
      uses: cpp-linter/cpp-linter-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        style: 'file'
        tidy-checks: 'readability-*,bugprone-*,misc-*,performance-*,modernize-*'
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
