name: 'C/CPP'
description: 'Lint C/CPP files'

runs:
  using: composite
  steps:
    - name: Install clang-format
      run: sudo apt install -qqy --no-install-recommends clang-format
    - name: Linters
      uses: wearerequired/lint-action@v2
      with:
        clang_format: true
