name: Build all

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        default: '3.12'
      rust_version:
        description: 'Rust version'
        default: 'stable'

jobs:
  build-rust:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('Cargo.toml') != '' }}
    steps:
      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ github.event.inputs.rust_version }}
          components: clippy, rustfmt
      - name: Cache rust
        uses: Swatinem/rust-cache@v2
      - name: Test rust
        run: cargo test
      - name: Build rust
        run: cargo build --release
