name: 'Lint basic'
description: 'Lint basic stuffs'

inputs:
  github_token:
    description: 'GITHUB_TOKEN secret'
    required: true

runs:
  using: composite
  steps:
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@master
    - name: Final newline
      uses: Logerfo/newline-action@0.0.4
      with:
        github-token: ${{ inputs.github_token }}
        config-path: .github/check/newline.yml
