name: 'Lint basic'

on:
  workflow_call:

jobs:
  lint-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
      - name: Final newline
        uses: Logerfo/newline-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/newline.yml
