name: 'Lint basic'

on:
  workflow_call:
    inputs:
      github-token:
        description: 'GitHub Token'
        required: true

jobs:
  lint-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
      - name: Final newline
        uses: Logerfo/newline-action@0.0.4
        with:
          github-token: ${{ inputs.github-token }}
          config-path: .github/newline.yml
